### ISSUE TITLE
TypeError: 'NoneType' object is not callable if get_s3 gets account_accessor=None

### ISSUE THREAD

**Issue by nmb10** [CivicKnowledge/ambry_sources#11]
get_s3 should validate account_accessor callable and its returned value.

The error (traceback from ambry lib):
```
Traceback (most recent call last):
  File "load_pre10.py", line 192, in <module>
    main()
  File "load_pre10.py", line 181, in main
    _ingest(b)
  File "load_pre10.py", line 120, in _ingest
    b.ingest(force=force, clean_files=clean_files)
  File "/home/nmb10/projects/ambry_project/ambry/bundle/bundle.py", line 874, in ingest
    s = get_source(source.spec, self.library.download_cache, clean=force)
  File "/home/nmb10/.virtualenvs/ambry/local/lib/python2.7/site-packages/ambry_sources/download.py", line 37, in get_source
    cache_path, download_time = download(spec.url, cache_fs, account_accessor, clean=clean)
  File "/home/nmb10/.virtualenvs/ambry/local/lib/python2.7/site-packages/ambry_sources/download.py", line 200, in download
    s3 = get_s3(url, account_accessor)
  File "/home/nmb10/.virtualenvs/ambry/local/lib/python2.7/site-packages/ambry_sources/download.py", line 266, in get_s3
    
TypeError: 'NoneType' object is not callable
```

**Comment by nmb10** [comment]
Done.
