### ISSUE TITLE
'tuple' object does not support item assignment error if header contains tuples.

### ISSUE THREAD

**Issue by nmb10** [CivicKnowledge/ambry_sources#27]
Simple example:
```python
>>> from ambry_sources.intuit import RowIntuiter
>>> RowIntuiter.coalesce_headers([('Header0', ''), ('Header1', ''), ('Header2', 'Header2')])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nmb10/projects/ambry_sources/ambry_sources/intuit.py", line 743, in coalesce_headers
    hl[i] = last
TypeError: 'tuple' object does not support item assignment

```

**Comment by nmb10** [comment]
Done.
